### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by dzheltkov** [UdalovaES/CppHomework#1]
1) Первое задание зачтено.

2) Нет проверки принадлежности точки стороне, второе задание пока незачтено.

3) Нет обработки ошибок ввода, не используются перечислимые типы, третье задание не зачтено.

4) Приведение угла к градучам излишне.

**Comment by UdalovaES** [comment]
Устранила ошибки, добавила третье задание.

**Comment by dzheltkov** [comment]
Второе и третье задание зачтены.
